version: '3.8'
services:
  server-rest:
    container_name: server-rest
    build:
      context: .
      target: development
    ports:
    - "5005:5005"
    - "8080:8080"
    environment:
      - SERVER_PORT=8080