= Bean

Nesse exemplo iremos verificar como criar um Java bean com a ajuda do nosso querido https://spring.io/[Spring], mas podemos utilizar as demais ferramentas disponíveis que nos auxiliam com esse processo que nos fornece o mesmo resultado, porém com técnias um pouco diferntes.

Um projeto com acoplamento zero não existe, até porque devemos desenvolvedor em módulos e, consequentemente, reaproveitar implementações, sendo assim as nossas classes sempre precisarão de implementações de "terceiros", porém controlar a criação de todas as instâncias necessárias em cada local que ela for utilizada, deixa o nosso projeto muito verboso e com responsabilidades distribuidas por todo canto, com isso o acoplamento fica muito alto e díficil manutenção.

Para diminuir esse acoplamento, iremos solicitar ao Spring que nos forneça uma instância da implementação que desejamos, sendo assim, utilizaremos o objeto sem nos preocupar de `como` e `quando` essa instância foi criada, essa tarefa será delegada a camada de infraestrutura do nosso projeto.

Aproveitaremos os benefícios da Injeção de Dependência para a utilização de um Java Bean.


== Injeção de Dependência

A `Injeção de Depência` (`Dependency Injection` ou `DI`) fornece uma das formas de implementar o padrão `Inversão de Controle` (`Inversion of Control` ou `IoC`). Nesse padrão o controle da criação de uma instância é delegado a uma infraestruta de código, deixando a classe que utilizará essa instância livre de preocupação de `como` criar a instância do objeto que irá utilizar, a classe ficará focada em apenas `utilizar` esse objeto. Com esse padrão a nossa classe terá um acoplamento mais baixa, facilitando a manutenção e deixando as responsabilidade bem definidas, e a `IoC` ajuda o desenvolvedor a atender a um dos princípios do `SOLID` o `Princípio da Responsabilidade Única`(Single Responsability Principle`). Uma importante observação que é se você utilizar `IoC` não significa que você atendeu o `Princípio da Responsabilidade Única` por completo, pois esse conceito é muito mais amplo do que apenas aplicar o `IoC`


== Criando o Bean

Para a criar um bean podemos reaproveitar os recursos do Spring e apenas anotar a nossa classe, ou ainda podemos criar uma "receita", ensisando o Spring como criar uma instância.

==== Pré requisitos

Nesse nosso exemplo, iremos utilizar o `Spring Boot`, para isso você deve configurar o seu arquivo `pom.xml`

Insira na tag `<project>` o seguinte parent com as configurações do Spring Boot

----
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.2.2.RELEASE</version>
	<relativePath/>
</parent>
----

Agora dentro da tag `<dependencies>`, insira a dependência do Spring Boot

----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter</artifactId>
</dependency>
----

Note no `<parent>` que configuramos a versão `2.2.2.RELEASE`, sendo assim, todas as dependências do Spring Boot irá obter essa versão.

==== Bean com anotação Spring

Iremos reproveitar a infraestrutura do `Spring` para nos auxiliar com a criação dos nossos beans. No Spring, quando anotamos uma classe com `@Component` do pacote `org.springframework.stereotype.Component`, ela se torna uma candidata a auto detecção do Spring. O que isso significa? Quando a JVM carregar o nosso projeto, o Spring varre todo o nosso projeto e as classes que estão com a anotação `@Component` o Spring sabe que deverá criar uma instância dela quando for solicitado.

Ela é uma classe candidata, pois o Spring não sabe de fato se será necessário criar uma instância dessa classe, pois você pode anotar essa classe para ser um bean, porém pode criar a instância em tempo de desenvolvimento utulizando o operado `new`, nada impede isso.

Para criar um bean utilizando a anotação é muito simples, basta criar uma classe e anotá-la com `@Component`:

----
package br.com.gilson.learning.beanexemplify.service;

import java.math.BigDecimal;

import org.springframework.stereotype.Component;

@Component
public class Calculadora {
	
	public BigDecimal somaDoisNumeros(BigDecimal firstNumber, BigDecimal secondNumber) {
		return firstNumber.add(secondNumber);
	}
}
----

Pronto, a nossa classe candidata a um Java Bean, utilizando a infraestrurada do Spring já está pronto, como como o Spring sabe que estamos delegando a ele a responsabilidade de fornecer uma instância de `Calculadora`? Como configurar o nosso atributo do tipo `Calculadora` para que receba a instância referente ao seu tipo ao invés do desenvolvedor criá-la em tempo de desenvolvimento com o operador `new`? Vamos verificar como configurar o Spring para injetar a instância que precisamos.

NOTE: Você ainda pode utilizar as anotações `@Service` do pacote `org.springframework.stereotype.Service`, `@Repository` do pacote `org.springframework.stereotype.Repository, e `@Controller` do pacote `org.springframework.stereotype.Controller`. Essas anotações possuem a anotação `@Component`, ou seja, tudo que a anotação `@Component` faz, essas anotações também fazem, porém qual a diferença? Com essas anotações você organiza o código. A anotação `@Service` é utiliza na sua camada de serviço, por exemplo, quando você cria suas interfaces de serviço você pode anotá-las como `@Service`, a anotação `@Repository` você utiliza na sua camada de persistência, já a anotação `@Controller` você utiliza na sua camada de controle, aonde você implementa os seus endpoints. 

==== Injetando o Bean

Agora para utilizar o nosso bean, você deve solicitar ao Spring que lhe forneça uma instância de Calculadora, invertendo o controle para que o Spring crie a instância em tempo de execução ao invés do desenvolvedor criá-la em tempo de desenvolvimento.
O Spring identifica na nossa aplicação todos os atributos que possuem a anotação `@Autowired` do pacote `org.springframework.beans.factory.annotation.Autowired`, nesse momento ele sabe que deverá fornecer uma instância daquele determinado tipo antes que seja invoca algum comportamento e/ou atributos daquele objeto. A instância não necessariamente será criada em tempo de compilação mas com toda certeza será injetada antes que seja invocado algum comportamento e/ou atributo do respectivo objeto, evitando assim o temido `NullPointerException`.

No exemplo abaixo, o Spring sabe que em algum momento, em tempo de execução, deverá fornecer uma instância do tipo Calculadora para essa classe consumidora.

----
@Autowired
private Calculadora calculadora;
----

E devemos apenas utilizar os comportamentos do nosso objeto, sem nenhuma preocupação de `como` e `quando` foi criado essa instância:

----
BigDecimal result = this.calculadora.somaDoisNumeros(first, second);
----

A nossa classe consumidora completa:

----
package br.com.gilson.learning.beanexemplify;

import static org.junit.jupiter.api.Assertions.assertEquals;
import java.math.BigDecimal;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import br.com.gilson.learning.beanexemplify.service.Calculadora;

@SpringBootTest
public class CalculadoraTest {
	
	@Autowired
	private Calculadora calculadora;
	
	@Test
	public void deveSomarDoisNumeros() {
		BigDecimal first = new BigDecimal("12");
		BigDecimal second = new BigDecimal("10");
		
		BigDecimal expected = first.add(second);
		
		BigDecimal result = this.calculadora.somaDoisNumeros(first, second);
		
		assertEquals(expected, result, "Result equals 22");
	}

}
----

A inversão de controle somente será possível (no caso do Java Bean), quando você anota a classe que será composta com `@Component` e na classe que compoem anota o atributo com `@Autowired`, se uma dessas anotações não forem configuradas, o Spring não será capaz de assumir o controle da criação da instância. Se você não configurar a anotação `@Autowired` no atributo e não criar a instância em tempo de desenvolvimento, quando tentar utilizar algum comportamento e/ou atributo do objeto será lançado a exceção `NullPointerExcption` em tempo de execução, agora se você não configurar a anotação `@Component`, em tempo de compilação será lançada a exceção `org.springframework.beans.factory.NoSuchBeanDefinitionException`.

Para que o Spring injete o Bean, o seu projeto precisa utilizar um contexto do Spring. Nesse nosso exemplo, a classe de teste utiliza o contexto do Spring que é fornecido com a configuração da anotação `@SpringBootTest` do pacote `org.springframework.boot.test.context.SpringBootTest`, porém quando você utiliza esse tipo de injeção de dependência nas suas classes da aplicação, você deve configurar a anotação `@SpringBootApplication` do pacote `org.springframework.boot.autoconfigure.SpringBootApplication`na classe `main`. Assim que a JVM carrega a sua aplicação, o Spring fornecerá um contexto que fará a gestão da infra-estrutura da sua aplicação forcendo todos os seus beans configurados, tanto por você quanto os que são configurados nas dependências que você utiliza no seu projeto. 

=== Configurando o seu Bean

Em algumas ocasiões você precisará ensinar o Spring como criar um Bean. Por exemplo, você criou a classe `CalculadoraComNome` aonde é necessário informar o nome da calculadora no construtor, passando um parâmetro do tipo String. 

Se você anotar a classe com `@Component`, o Spring não tem como saber o que informar no construtor, e em tempo de compilação será lançado a exceção `org.springframework.beans.factory.NoSuchBeanDefinitionException` informando que não possui um bean qualificado disponível.

Nesse caso iremos orientar o Spring a criar uma instância de `CalculadoraComNome`, informando um nome no parâmetro.

Para configurar o nosso bean, precisamos de uma classe de configuração, pois ao carregar a aplicação na JVM, o Spring analisará todas as nossas configurações pré-estabelecida. Para isso crie uma classe com a anotação `@Configuration` do pacote `org.springframework.context.annotation.Configuration`

----
@Configuration
public class ConfigurationExemplify {

}
----

Agora vamos instruir o Spring a criar o nosso Bean. Para isso crie um método com o tipo de retorno da instância que será criado o nosso bean, no nosso exemplo `CalculadoraComNome` e anote esse método com `@Bean` do pacote `org.springframework.context.annotation.Bean`. O nome do método você que decide, porém não pode conter parâmetros. 

----
@Bean
public CalculadoraComNome getCalculadoraComNome() {
	return new CalculadoraComNome("HP");
}
----

NOTE: Na verdade você até pode inserir parâmetro nos métodos de configuração do Bean, porém o tipo desse parâmetro precisa ser injetado pelo Spring. 

Segue um exemplo da nossa classe `CalculadoraComNome`:

----
package br.com.gilson.learning.beanexemplify.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import br.com.gilson.learning.beanexemplify.service.CalculadoraComNome;

@Configuration
public class ConfigurationExemplify {

	@Bean
	public CalculadoraComNome getCalculadoraComNome() {
		return new CalculadoraComNome("HP");
	}
}
----

A injeção dessa depdência é identico quando utilizamos o `@Compoenent`, devemos apenas anotar a nossa propriedade com o `@Autowired` que o Spring fará a injenção desse tipo em tempo de execução, olhe o teste abaixo:

----
package br.com.gilson.learning.beanexemplify;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.blankOrNullString;
import static org.hamcrest.Matchers.not;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import br.com.gilson.learning.beanexemplify.service.CalculadoraComNome;

@SpringBootTest
public class CalculadoraComNomeTest {
	
	@Autowired
	private CalculadoraComNome calculadoraHP;
	
	@Test
	public void calculadoraDevePossuirUmNome() {
		
		assertThat( "Calculador não pode ter nome nulo ou vazio", this.calculadoraHP.getNome(), not(blankOrNullString()));
	}

}

----

Uma aplicação pode ter nenhuma ou várias classes de configuração personalizada, e dentro de cada classe de configuração pode ter um ou mais métodos de configuração de Bean. Se você configurar mais um Bean com o mesmo tipo, você deve identificá-lo. Por exemplo, caso você crie duas calculadoras, uma HP e outra Genéric, você deverá criar dois beans para o mesmo tipo porém com a devida identificação. Para identificar um Bean você pode informar no parâmetro `name` da anotação `@Bean` ou adicionar a notação `@Qualifier` do pacote `org.springframework.beans.factory.annotation.Qualifier` no método de configuração do Bean e informar o identificador. Observe no exemplo abaixo que criamos dois beans com o mesmo tipo, porém no primeiro exemplo informamos o identificar no parâmetro da anotação `Bean` e no segundo adicionamos a anotação `Qualifier`, ambos com o mesmo efeito.

----
package br.com.gilson.learning.beanexemplify.config;

import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import br.com.gilson.learning.beanexemplify.service.CalculadoraComNome;

@Configuration
public class ConfigurationExemplify {
	
	@Bean(name = "HP")
	public CalculadoraComNome getCalculadoraComNomeHP() {
		return new CalculadoraComNome("HP");
	}
	
	@Bean
	@Qualifier("Generic")
	public CalculadoraComNome getCalculadoraComNomeGeneric() {
		return new CalculadoraComNome("Genérico");
	}
}
----

Agora para utilizar o nosso Bean, devemos adicionar a anotação `Qualifier` na propriedade e informar o nome do Bean que desejamos utilizar. Veja:

----
package br.com.gilson.learning.beanexemplify;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.blankOrNullString;
import static org.hamcrest.Matchers.not;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;

import br.com.gilson.learning.beanexemplify.service.CalculadoraComNome;

@SpringBootTest
public class CalculadoraComNomeTest {

	@Autowired
	@Qualifier("HP")
	private CalculadoraComNome calculadoraHP;
	
	@Autowired
	@Qualifier("Generic")
	private CalculadoraComNome calculadoraGeneric;
	
	@Test
	public void calculadoraDevePossuirUmNome() {
		
		assertThat("Calculador não pode ter nome nulo ou vazio", this.calculadoraHP.getNome(), not(blankOrNullString()));
	}
	
	@Test
	public void calculadoraDevePossuirNomeHP() {
		
		assertEquals("HP", this.calculadoraHP.getNome(), "Calculadora HP");
	}
	
	@Test
	public void calculadoraDevePossuirNomeGeneric() {
		
		assertEquals("Genérico", this.calculadoraGeneric.getNome(), "Calculadora Genérica");
	}

}
----


== Conclusão

Essa é uma das formas que criamos e utilizamos nossos Beans no Spring com o benefício das anotações, note que ficou bem simples e tudo configurado programaticamente, nada de XML.

Você possui outras formas para configurar o seu Bean, inclusive utilizando o XML.

Você também possui outras ferramentas que nos auxiliam com a Inversão de Controle e Injeção de dependência, o universo do Java é amplo e praticamente quase em tudo possui mais de uma maneira de fazer a coisa certa.
